const frame=require('./apply_frame.cjs');
/* 同内容对照：中文长标题、英文分析页、混排财务表；全部数字为合成示意。 */
const fs=require('node:fs'),path=require('node:path'),type=require('../assets/deck-typography.js'),themes=require('../assets/deck-themes.js'),kit=require('../assets/exhibit-kit.js'),{pack}=require('./pack_fonts.cjs');
const root=path.resolve(__dirname,'..');
function build(out,profile='serif-report',theme='mckinsey'){
 const p=type.get(profile),palette=themes.palette(theme),slides=[];
 const page=(title,lead,body,lang='zh-CN')=>{const n=slides.length+1;slides.push(`<section class="slide reading analytical${n===1?' active':''}" lang="${lang}">${frame.markup}<div class="slide__tracker">字体与排版验证 · ${p.id}</div><div class="slide__sticker">示意数据 · 非真实结论</div><header class="slide__header"><h1 class="slide__title">${title}</h1><div class="slide__lead">${lead}</div></header><div class="slide__body">${body}</div><div class="source">来源：本技能固定合成数据。用途：比较字体层级、长标题、混排、数字对齐与打印效果；不用于经营决策。</div><div class="slide__page">${n}</div></section>`);};
 const graph=kit.dumbbell({typography_id:profile,palette,width:740,height:300,fontSize:16,startLabel:'2024年',endLabel:'2025年',items:[{label:'企业客户',start:6.4,end:8.2},{label:'中小企业',start:3.1,end:3.5},{label:'个人客户',start:1.8,end:2.7}]});
 page('收入增长27%，但利润改善仍取决于客户结构与履约效率','同一组模拟数据：先核对规模变化，再检验增长能否转化为利润。',`<div class="comparison-layout"><div class="exhibit"><h2>01｜增长主要来自企业客户</h2><div class="unit">收入，亿元；空心=2024年，实心=2025年</div>${graph}<p class="type-note">总收入：11.3 → 14.4 亿元；增长率=(14.4−11.3)/11.3≈27%。</p></div><div class="exhibit"><h2>02｜需要验证的经营条件</h2><div class="evidence-note"><strong>结构｜企业客户贡献58%增量</strong>企业客户增加1.8亿元，占总增量3.1亿元的约58%。贡献分解不等于因果判断。</div><div class="evidence-note"><strong>效率｜收入增长不等于利润增长</strong>补充交付成本、续约率与应收账期，核验规模扩张后的单位经济性。</div><p class="type-note">分析边界：示例没有利润数据，因此不能据此判断盈利改善。</p></div></div>`);
 page('Revenue growth is concentrated in enterprise accounts, while profitability remains unverified','Illustrative operating review · Keep the conclusion, evidence and limitations visually distinct.',`<div class="comparison-layout"><div class="exhibit"><h2>01 | Revenue bridge</h2><table class="data-table"><thead><tr><th>Segment</th><th class="num">2024</th><th class="num">2025</th><th class="num">Change</th></tr></thead><tbody><tr><td>Enterprise</td><td class="num">6.40</td><td class="num">8.20</td><td class="num">+1.80</td></tr><tr><td>SMB</td><td class="num">3.10</td><td class="num">3.50</td><td class="num">+0.40</td></tr><tr><td>Consumer</td><td class="num">1.80</td><td class="num">2.70</td><td class="num">+0.90</td></tr><tr><td><strong>Total</strong></td><td class="num">11.30</td><td class="num">14.40</td><td class="num">+3.10</td></tr></tbody></table><p class="type-note">Unit: RMB 100 million. Rounded values preserve the revenue bridge.</p></div><div class="exhibit"><h2>02 | Questions for the next review</h2><div class="evidence-note"><strong>Test the margin mechanism</strong>Separate pricing, delivery cost and account mix before attributing profit improvement to scale.</div><div class="evidence-note"><strong>Check cash conversion</strong>Compare renewal rates and receivable days across the same customer cohorts.</div><p class="type-note">Limitation: profit and cash-flow observations are not available in this illustrative dataset.</p></div></div>`,'en');
 page('财务表优先保证数字对齐，标题中的2026与13%保持叙述风格','混排测试：Revenue / EBITDA / CAGR；负数、百分比、货币与缺失值各自保留明确含义。',`<div class="exhibit"><h2>01｜经营指标复核 · Management review</h2><table class="data-table finance"><colgroup><col style="width:28%"><col style="width:16%"><col style="width:16%"><col style="width:16%"><col style="width:24%"></colgroup><thead><tr><th>指标 / Metric</th><th class="num">2024</th><th class="num">2025</th><th class="num">差额 / Δ</th><th>核对要点</th></tr></thead><tbody><tr><td>收入 / Revenue，万元</td><td class="num">11,111.00</td><td class="num">18,888.00</td><td class="num">+7,777.00</td><td>统一期间与币种</td></tr><tr><td>经营利润 / EBIT，万元</td><td class="num">−1,234.50</td><td class="num">1,234.50</td><td class="num">+2,469.00</td><td>负基数不计算同比率</td></tr><tr><td>毛利率 / Gross margin</td><td class="num">31.10%</td><td class="num">33.80%</td><td class="num">+2.70 pp</td><td>百分点与百分比分开</td></tr><tr><td>海外收入 / USD，万元</td><td class="num">$888.00</td><td class="num">$999.00</td><td class="num">+$111.00</td><td>币种另列，不与人民币合计</td></tr><tr><td>现金流 / Cash flow</td><td class="num">0.00</td><td class="num">—</td><td class="num">—</td><td>缺失不能当作零</td></tr></tbody></table><p class="type-note">重要口径：本页各行均为独立字体测试数据，不与前两页合并。标题中的2026与13%只用于混排检验。</p><p class="type-note">数据列使用齐线等宽数字；说明文字保持比例字形。备注维持可读字号，不用极浅颜色隐藏边界。</p></div>`);
 let html=fs.readFileSync(path.join(root,'assets/deck_engine.html'),'utf8');html=html.slice(html.indexOf('<!DOCTYPE html>'));const start=html.indexOf('<section class="slide'),end=html.indexOf('</div></div><!-- /stage /viewport -->');html=html.slice(0,start)+slides.join('\n')+html.slice(end);
 html=html.replace(/<script src="[^"]+"><\/script>/g,'').replace(/<script type="module">[\s\S]*?<\/script>/g,'').replace('<title>Deck Title</title>',`<title>字体对照 · ${profile}</title>`);
 const css=fs.readFileSync(path.join(root,'assets/consulting-layouts.css'),'utf8')+'\n.comparison-layout{display:grid;grid-template-columns:740px 436px;gap:24px}.comparison-layout svg{flex:none;max-width:100%}.type-note{margin-top:16px}.finance td{padding:18px 9px}.slide.reading{--frame-rule-offset:-11px}.reading .slide__body{margin-top:22px}.reading .source{margin-top:auto}';
 html=html.replace('</style>',css+'\n</style>');html=pack(frame.apply(themes.apply(html,theme)),{profile});fs.mkdirSync(out,{recursive:true});const file=path.join(out,profile+'.html');fs.writeFileSync(file,html);return file;
}
if(require.main===module){const dir=path.resolve(process.argv[2]||'typography-preview');for(const id of ['legacy-system','serif-report','serif-playfair'])console.log(build(dir,id));}
module.exports={build};
