/* 若图表仍使用独立 Arial 字体链、非法配置静默回退或离线资源漏打包，本测试应失败。 */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const runtime=require('../assets/chart-runtime.js'),themes=require('../assets/deck-themes.js');
const settings={width:720,height:360,tokens:themes.get().tokens,typography_id:'serif-report'};
const plan=runtime.prepare('rankedBar',{items:[{label:'收入 Revenue',value:1234.5}]},settings);
assert.match(plan.pages[0].option.textStyle.fontFamily,/Deck Inter/,'配方必须使用可打包的统一正文西文字体');
assert.match(plan.pages[0].option.textStyle.fontFamily,/Deck Noto Sans SC/,'配方必须包含统一中文字体');
assert.throws(()=>runtime.prepare('rankedBar',{items:[{label:'收入',value:1}]},{...settings,typography_id:'unknown'}),/字体|typography/);
const type=require('../assets/deck-typography.js'),kit=require('../assets/exhibit-kit.js');
assert.equal(type.get('serif-report').weights.titleLatin,400);
assert.equal(type.get('serif-playfair').weights.titleLatin,500);
assert.throws(()=>type.get('__proto__'),/字体/);
const svg=kit.dumbbell({items:[{label:'收入 Revenue',start:10,end:12}]});
assert.match(svg,/Deck Inter/);assert.doesNotMatch(svg,/Arial/);
assert.match(kit.dumbbell({typography_id:'legacy-system',items:[{label:'收入',start:1,end:2}]}),/Arial/);
const {pack}=require('./pack_fonts.cjs');
const html='<html lang="zh-CN"><head></head><body><h1 class="slide__title">增长13%：Revenue</h1><p>收入 −1,234.50 亿元</p></body></html>';
const packed=pack(html,{profile:'serif-report'});
assert.match(packed,/data:font\/woff2;base64,/);assert.match(packed,/data-typography="serif-report"/);
assert.doesNotMatch(packed,/@import|fonts\.googleapis/);
assert.equal((pack(packed,{profile:'serif-report'}).match(/id="deck-fonts"/g)||[]).length,1,'重复打包必须替换旧资源');
assert.throws(()=>pack(html.replace('增长','\u{10FFFF}'),{profile:'serif-report'}),/字形|glyph/,'缺失字形不能静默丢弃');
assert.throws(()=>pack(html.replace('增长','Ċ'),{profile:'serif-report'}),/title.*字形|字形.*title/,'正文支持的字符不能掩盖标题字体链缺字');
assert.doesNotThrow(()=>pack(html.replace('<p>收入','<p>Ċ 收入'),{profile:'serif-report'}),'正文可用Inter字形不应被标题字体误拦截');
const entity=pack('<html><head></head><body><p>Brand&trade;</p><div data-spec=\'{"label":"&bull;"}\'></div></body></html>',{profile:'serif-report'}),entityFaces=JSON.parse(entity.match(/id="deck-font-manifest"[^>]*>(.*?)<\/script>/s)[1]).faces;
assert.ok(entityFaces.some(f=>f.family==='Deck Inter'&&f.sample.includes('™')),'命名实体的可见字形须进入子集');
assert.ok(entityFaces.some(f=>f.sample.includes('•')),'data-spec实体解码后须进入子集');
const escapedJSON=pack('<html><head></head><body><div data-spec=\'{"label":"\\u96ea"}\'></div></body></html>',{profile:'serif-report'}),jsonFaces=JSON.parse(escapedJSON.match(/id="deck-font-manifest"[^>]*>(.*?)<\/script>/s)[1]).faces;
assert.ok(jsonFaces.some(f=>f.sample.includes('雪')),'JSON转义后的真实字符须进入子集');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'deck-font-negative-'));
assert.throws(()=>pack(html,{profile:'serif-report',assetDir:tmp}),/资源|manifest|ENOENT/,'缺少字体资源不能标称自包含');
console.log('PASS: 统一字体、配置拒绝、真实字重、SVG继承、子集嵌入、幂等、缺字和缺资源拒绝');
