/* 自由四页片段→原引擎→真实离线Chrome/PDF；不重新测试图型算法。 */
'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{pathToFileURL}=require('node:url');
const {assemble}=require('./assemble_deck.cjs');let pw;try{pw=require('playwright');}catch{pw=require(process.env.PLAYWRIGHT_MODULE||process.env.PLAYWRIGHT_PATH);}
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'deck-assembly-test-'));let browser;const results={};try{
 const input=path.join(dir,'pages.html'),output=path.join(dir,'deck.html'),css=path.join(dir,'page.css');
 const section=(n,body)=>'<section class="slide reading" data-frame-boundary="integrated"><header class="slide__header"><h1 class="slide__title">第'+n+'页：中文与 SVG 123</h1></header><div class="slide__body">'+body+'</div><div class="source">合成测试材料，不代表行业事实。</div><div class="slide__page">'+n+'</div></section>';
 const pages='<style>.reading .slide__title{max-width:1100px}.author-test{color:var(--brand)}</style>'+section(1,'<div class="layout-split"><p class="author-test">自由主辅布局</p><p>独立补充</p></div>')+section(2,'<table><tr><th>类别</th><th>数值</th></tr><tr><td>长中文类别</td><td>2,250</td></tr></table>')+section(3,'<svg viewBox="0 0 600 200" width="600" height="200"><defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z"/></marker></defs><rect x="30" y="30" width="180" height="60" fill="var(--brand)"/><text x="30" y="125" font-size="20">静态SVG文本 82 → 90</text><path d="M230 60H370" stroke="var(--brand)" marker-end="url(#arrow)"/></svg>')+section(4,'<p>末页自由正文，保留任意证据结构。</p>');
 fs.writeFileSync(input,pages);fs.writeFileSync(css,'.slide__body{align-content:start}.author-test{font-weight:600}');
 const result=await assemble({pagesFile:input,outputFile:output,cssFile:css,title:'自由装配四页',kind:'fragment'});assert.equal(result.pages,4);assert.equal(result.status,'assembled');results.assembled='PASS';
 const html=fs.readFileSync(output,'utf8');for(const id of ['deck-layouts','deck-geometry','deck-fonts','deck-font-manifest','deck-frame','deck-bookends','deck-author'])assert.ok(html.includes('id="'+id+'"'),id);
 assert.ok(html.includes('data:font/woff2;base64,'));assert.ok(!html.includes('北辰食品'));assert.ok(!html.includes('Executive summary'));results.inline_resources='PASS';
 browser=await pw.chromium.launch({channel:process.env.CHROME_CHANNEL||'chrome',headless:true});const context=await browser.newContext({offline:true,viewport:{width:1400,height:900}}),p=await context.newPage(),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('request',r=>{if(!r.url().startsWith('file:')&&!r.url().startsWith('data:'))requests.push(r.url());});
 await p.goto(pathToFileURL(output).href+'#3');await p.evaluate(()=>window.deckReady);assert.equal(await p.locator('script[src],link[href]').count(),0);assert.equal(await p.locator('#stage > .slide').count(),4);assert.equal(await p.locator('.slide.active .slide__page').textContent(),'3');assert.equal(await p.locator('.slide.active svg text').textContent(),'静态SVG文本 82 → 90');assert.equal(await p.locator('.slide__frame').count(),4);assert.equal(await p.locator('.slide').first().getAttribute('data-frame-boundary'),'integrated');
 await p.keyboard.press('Home');assert.equal(await p.locator('.layout-split').evaluate(e=>getComputedStyle(e).display),'grid');assert.equal(await p.locator('.author-test').evaluate(e=>getComputedStyle(e).color),'rgb(0, 0, 128)');assert.equal(await p.locator('html').getAttribute('data-font-status'),'ready');
 await p.keyboard.press('g');assert.equal(await p.locator('.slide:visible').count(),4);await p.keyboard.press('Escape');await p.keyboard.press('End');assert.equal(await p.locator('.slide.active .slide__page').textContent(),'4');
 const pdf=path.join(dir,'deck.pdf');await p.pdf({path:pdf,preferCSSPageSize:true,printBackground:true});assert.match(execFileSync('pdfinfo',[pdf],{encoding:'utf8'}),/Pages:\s+4/);const text=execFileSync('pdftotext',[pdf,'-'],{encoding:'utf8'}).replace(/\s/g,'');for(let n=1;n<=4;n++)assert.ok(text.includes('第'+n+'页'));assert.ok(text.includes('静态SVG文本'));assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);results.offline_navigation_pdf='PASS';
 const alternate=path.join(dir,'alternate.html');await assemble({pagesFile:input,outputFile:alternate,theme:'bcg',typography:'sans-presentation',ratio:'4x3'});
 await p.goto(pathToFileURL(alternate).href+'#3');await p.evaluate(()=>window.deckReady);assert.equal(await p.locator('#stage').evaluate(e=>getComputedStyle(e).width),'1024px');assert.equal(await p.locator('html').getAttribute('data-theme'),'bcg');assert.equal(await p.locator('html').getAttribute('data-typography'),'sans-presentation');
 const altPdf=path.join(dir,'alternate.pdf');await p.pdf({path:altPdf,preferCSSPageSize:true,printBackground:true});const altInfo=execFileSync('pdfinfo',[altPdf],{encoding:'utf8'});assert.match(altInfo,/Pages:\s+4/);assert.match(altInfo,/Page size:\s+768 x 576 pts/);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);results.alternate_theme_type_ratio='PASS';
 const modes=path.join(dir,'modes.html'),modeOutput=path.join(dir,'modes-output.html');fs.writeFileSync(modes,section(1,'<p>保留presentation模式</p>').replace('class="slide reading"','class="slide"')+section(2,'<p>保留reading模式</p>')+'<section class="slide cover" data-page-role="cover" data-frame="off" data-frame-boundary="space"><h1 class="cover-title">首尾边界由作者声明</h1></section>');
 await assemble({pagesFile:modes,outputFile:modeOutput});await p.goto(pathToFileURL(modeOutput).href);await p.evaluate(()=>window.deckReady);
 assert.equal(await p.locator('.slide').nth(0).evaluate(e=>e.classList.contains('reading')),false);assert.equal(await p.locator('.slide').nth(1).evaluate(e=>e.classList.contains('reading')),true);assert.equal(await p.locator('.slide').nth(2).getAttribute('data-frame-boundary'),'space');assert.equal(await p.locator('.slide').nth(2).getAttribute('data-frame'),'off');results.author_mode_and_boundary='PASS';
 const negative=[['empty',''],['full_document','<html><body>'+section(1,'x')+'</body></html>'],['unclosed','<section class="slide"><p>x</p>'],['not_slide','<section><p>x</p></section>'],['nested',section(1,section(2,'x'))],['dynamic',section(1,'<div class="chart" data-opt="{}"></div>')],['canvas',section(1,'<canvas></canvas>')],['script',section(1,'<script>window.x=1</script>')],['handler',section(1,'<p onclick="x()">x</p>')],['remote_image',section(1,'<img src="https://invalid.example/image.png">')],['remote_css','<style>.x{background:url(https://invalid.example/a.png)}</style>'+section(1,'x')],['import_css','<style>@\\69mport "https://invalid.example/a.css";</style>'+section(1,'x')],['reserved_id',section(1,'<div id="hud">x</div>')],['duplicate_id',section(1,'<p id="same">x</p><p id="same">y</p>')]];
 for(const [name,value]of negative){const f=path.join(dir,name+'.html'),out=path.join(dir,name+'-out.html');fs.writeFileSync(f,value);await assert.rejects(()=>assemble({pagesFile:f,outputFile:out}),undefined,name);assert.ok(!fs.existsSync(out));results[name]='FAIL_AS_EXPECTED';}
 for(const [name,replace]of [['missing_boundary',''],['invalid_boundary','data-frame-boundary="off"']]){const f=path.join(dir,name+'.html'),out=path.join(dir,name+'-out.html');fs.writeFileSync(f,section(1,'x').replace('data-frame-boundary="integrated"',replace));await assert.rejects(()=>assemble({pagesFile:f,outputFile:out}),/data-frame-boundary/);assert.ok(!fs.existsSync(out));results[name]='FAIL_AS_EXPECTED';}
 const previousChannel=process.env.CHROME_CHANNEL,originalMkdtemp=fs.mkdtempSync;let createdTemp;
 try{fs.mkdtempSync=function(prefix,...rest){const made=originalMkdtemp.call(fs,prefix,...rest);if(path.basename(prefix)==='deck-assemble-')createdTemp=made;return made;};process.env.CHROME_CHANNEL='assembly-test-nonexistent-channel';await assert.rejects(()=>assemble({pagesFile:input,outputFile:path.join(dir,'launch-failure.html')}));}
 finally{fs.mkdtempSync=originalMkdtemp;if(previousChannel===undefined)delete process.env.CHROME_CHANNEL;else process.env.CHROME_CHANNEL=previousChannel;}
 assert.ok(createdTemp);assert.ok(!fs.existsSync(createdTemp));assert.ok(!fs.existsSync(path.join(dir,'launch-failure.html')));results.launch_failure_cleanup='PASS';
 await assert.rejects(()=>assemble({pagesFile:input,outputFile:input}));await assert.rejects(()=>assemble({pagesFile:input,outputFile:output,typography:'legacy-system'}));results.invalid_options='FAIL_AS_EXPECTED';
 console.log(JSON.stringify({pass:true,cases:Object.keys(results).length,results}));
 }finally{if(browser)await browser.close();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
