/* 真实数值不变式、可变布局及能检出目标错误的反例。运行不会改写验收产物。 */
const assert=require('node:assert/strict'),G=require('../assets/exhibit-geometry.js'),R=require('./render_precision_exhibit.cjs');
const samples={
  continuous:{type:'columns',title:'收入连续变化',unit:'单位：百万元',width:960,height:500,items:[{id:'y23',label:'2023 年',value:80.25},{id:'y24',label:'2024 年',value:102.5},{id:'y25',label:'2025 年',value:126.75}],connections:{mode:'continuous',style:'dashed'},comparisons:[{from:'y23',to:'y25'}],format:{decimals:2}},
  waterfall:{type:'waterfall',title:'现金流增减与小计闭合',unit:'单位：百万元',width:1080,height:520,items:[{id:'opening',label:'期初现金',type:'total',value:100},{id:'sales',label:'经营收款',type:'delta',value:32.5},{id:'cost',label:'采购及费用',type:'delta',value:-18.25},{id:'subtotal',label:'经营后小计',type:'subtotal',value:114.25},{id:'capital',label:'资本变动净额',type:'delta',value:5.75},{id:'closing',label:'期末现金',type:'total',value:120}],connections:{mode:'cumulative'},comparisons:[{from:'opening',to:'closing'}],format:{decimals:2}},
  smallStack:{type:'stacked',title:'小片组成与总量、指定层比较',unit:'单位：百万元',width:960,height:560,items:[{id:'before',label:'调整前',segments:[{id:'core',label:'核心收入',value:80},{id:'new',label:'新业务',value:2},{id:'other',label:'其他',value:.5}]},{id:'after',label:'调整后',segments:[{id:'core',label:'核心收入',value:110},{id:'new',label:'新业务',value:5},{id:'other',label:'其他',value:.2}]}],comparisons:[{from:'before',to:'after'},{from:{item:'before',series:'other'},to:{item:'after',series:'other'}}],format:{decimals:1}},
  axisBreak:{type:'columns',title:'极端量级的显式断轴',unit:'单位：万元',width:960,height:520,items:[{id:'domestic',label:'国内核心客户收入（含订阅服务）',value:10800.25},{id:'overseas',label:'海外企业客户收入（持续业务口径）',value:11240.5}],axisBreaks:[{from:1000,to:10000,gap:20}],comparisons:[{from:'domestic',to:'overseas'}],connections:{mode:'continuous'},format:{decimals:2}},
  negative:{type:'waterfall',title:'负值、小数与负基数增长率',unit:'单位：百万元',width:960,height:520,items:[{id:'opening',label:'期初',type:'total',value:12.5},{id:'loss',label:'收款减少',type:'delta',value:-20.75},{id:'subtotal',label:'小计',type:'subtotal',value:-8.25},{id:'renewal',label:'续约补回',type:'delta',value:3.5},{id:'closing',label:'期末',type:'total',value:-4.75}],connections:{mode:'cumulative'},comparisons:[{from:'subtotal',to:'closing'}],format:{decimals:2}},
  columnTotals:{type:'columns',title:'来源分量与真实合计',unit:'单位：百万元',width:960,height:500,items:[{id:'a',label:'订阅服务',value:18.5},{id:'b',label:'实施服务',value:7.25},{id:'s',label:'业务收入小计',type:'subtotal',value:25.75,sumOf:['a','b']},{id:'c',label:'其他收入',value:1.5},{id:'t',label:'收入合计',type:'total',value:27.25,sumOf:['s','c']}],format:{decimals:2}}
};
function run(){
  let checks=0;const check=(name,fn)=>{fn();checks++;};
  check('语义数值',()=>{assert.equal(G.semanticFormat(-3.5,{kind:'delta',decimals:1}),'−3.5');assert.equal(G.semanticFormat(.015,{kind:'rate',decimals:1}),'+1.5%');assert.equal(G.semanticFormat(.035,{kind:'pp',basis:'fraction',decimals:1}),'+3.5 个百分点');assert.equal(G.semanticFormat(1.2,{kind:'multiple',decimals:1}),'1.2×');assert.notEqual(G.semanticFormat(.00015,{decimals:2}),'0.00');assert.equal(G.change(0,10).rate,null);assert.equal(G.change(-5,10).rateStatus,'negative-base');assert.equal(G.change(80,100).rate,.25);assert.throws(()=>G.semanticFormat(1,{kind:'pp'}),/basis/);});
  check('显式断轴',()=>{const scale=G.createScale([0,12000],[400,40],{breaks:[{from:1000,to:10000,gap:20}]});assert.equal(scale.map(0),400);assert.equal(scale.map(12000),40);assert.ok(Math.abs(scale.map(1000)-scale.map(10000)-20)<1e-9);assert.equal(scale.segments(0,11000).length,2);assert.throws(()=>scale.map(5000),/断层/);assert.throws(()=>G.createScale([-20,20],[0,300],{breaks:[{from:-2,to:4}]}),/零点/);});
  check('共同行轨道',()=>{const rows=G.rowTracks([{lines:['中文','Revenue']},{lines:['数字']}],{top:10,fontSize:16,lineHeight:24,gap:8,right:300});assert.ok(Math.abs(rows[0].lastBaseline-rows[0].firstBaseline-24)<1e-9);assert.equal(rows[0].center,34);assert.equal(rows[1].top,66);assert.equal(rows[0].right,rows[1].right);});
  for(const [name,spec] of Object.entries(samples))check('代表 '+name,()=>{const built=R.build(spec);assert.equal(built.audit.ok,true);assert.doesNotMatch(built.svg,/NaN|Infinity|undefined/);assert.match(built.svg,/data-item=/);assert.equal(built.geometry.labels.filter(v=>v.role==='value').length,built.geometry.marks.length);});
  check('数据修改更新几何和派生',()=>{const before=R.build(samples.continuous),spec=structuredClone(samples.continuous);spec.items[2].value=140.5;const after=R.build(spec);assert.equal(after.geometry.routes.find(r=>r.role==='comparison').delta,60.25);assert.notEqual(before.geometry.anchors.y24.y,after.geometry.anchors.y24.y);});
  check('尺寸修改重新测量布置',()=>{for(const [name,source] of Object.entries(samples)){const spec={...structuredClone(source),width:source.width+120,height:source.height+90};const built=R.build(spec);assert.ok(built.audit.ok,name);assert.equal(built.geometry.width,spec.width);}});
  check('小画布、混排与长中文',()=>{const spec={...structuredClone(samples.continuous),width:720,height:440};spec.items[1].label='国内 Enterprise 客户\n持续经营业务';assert.ok(R.build(spec).audit.ok);});
  check('细小堆积外置引线及真实层值',()=>{const built=R.build(samples.smallStack);assert.ok(built.geometry.routes.filter(r=>r.role==='leader').length>=4);const comparison=built.geometry.routes.filter(r=>r.role==='comparison')[1];assert.equal(comparison.delta,-.3);assert.equal(comparison.axisFrom,.5);assert.equal(comparison.axisTo,.2);assert.equal(comparison.space,'layer-value');assert.ok(comparison.arrowAt.x<comparison.arrowFrom.x);const track=built.geometry.layerTracks[0];assert.equal(track.bars[0].rect.x,track.bars[1].rect.x);assert.ok(Math.abs(track.bars[1].rect.width/track.bars[0].rect.width-.4)<1e-8);assert.equal(comparison.rate,-.6);assert.match(built.svg,/Δ 层值/);});
  check('负值瀑布跨零闭合',()=>{const built=R.build(samples.negative);assert.equal(built.geometry.marks.find(v=>v.item==='loss').to,-8.25);assert.equal(built.geometry.routes.find(v=>v.role==='comparison').rateStatus,'negative-base');assert.match(built.svg,/增长率不适用（负基数）/);});
  check('零基数不伪造百分比',()=>{const built=R.build({type:'columns',items:[{id:'a',label:'试点前',value:0},{id:'b',label:'试点后',value:5}],comparisons:[{from:'a',to:'b'}]});assert.equal(built.geometry.routes.find(v=>v.role==='comparison').rate,null);assert.match(built.svg,/增长率不适用（零基数）/);});
  check('断轴与负值组合',()=>{const spec={type:'waterfall',width:1080,height:580,items:[{id:'a',label:'期初',type:'total',value:11000},{id:'b',label:'费用',type:'delta',value:-500},{id:'c',label:'期末',type:'total',value:10500}],axisBreaks:[{from:1000,to:10000,gap:18}],comparisons:[{from:'a',to:'c'}],connections:{mode:'cumulative'}};const built=R.build(spec);assert.ok(built.audit.ok);assert.equal(built.geometry.marks[0].pieces.length,2);assert.match(built.svg,/数值轴省略 1,000–10,000/);assert.match(built.svg,/data-role="mark-break"/);const crossed=R.build({type:'columns',width:960,height:540,items:[{id:'a',label:'试点',value:500},{id:'b',label:'推广',value:11000}],axisBreaks:[{from:1000,to:10000,gap:18}],connections:{mode:'continuous'},comparisons:[{from:'a',to:'b'}]});assert.match(crossed.svg,/data-role="route-break"/);});
  check('字号和实际600测量',()=>{const built=R.build({...structuredClone(samples.columnTotals),fontSize:18,width:1120,height:580});assert.ok(built.audit.ok);assert.equal(built.geometry.labels.find(l=>l.item==='t'&&l.role==='value').weight,600);});
  check('未闭合拒绝',()=>{const spec=structuredClone(samples.waterfall);spec.items.at(-1).value=119;assert.throws(()=>R.build(spec),/总计/);const col=structuredClone(samples.columnTotals);col.items[2].value=26;assert.throws(()=>R.build(col),/闭合/);const stack=structuredClone(samples.smallStack);stack.items[0].total=999;assert.throws(()=>R.build(stack),/系列之和/);});
  check('语义不明、漏项和截断拒绝',()=>{assert.throws(()=>R.build({...samples.continuous,connections:{mode:'unordered'}}),/关系/);assert.throws(()=>R.build({...samples.continuous,domain:[50,150]}),/零点/);const stack=structuredClone(samples.smallStack);stack.items[1].segments.pop();assert.throws(()=>R.build(stack),/全部系列/);const b=structuredClone(samples.axisBreak);b.items[0].value=6000;assert.throws(()=>R.build(b),/断层/);});
  check('反例：数值尺度位移4px被检出',()=>{const model=structuredClone(R.build(samples.axisBreak).geometry);model.marks[0].pieces[0].y+=4;assert.ok(R.auditLayout(model).issues.some(v=>v.code==='mark-scale'));});
  check('反例：比较端点位移4px被检出',()=>{const model=structuredClone(R.build(samples.continuous).geometry);model.routes.find(v=>v.role==='comparison').points[0].y+=4;assert.ok(R.auditLayout(model).issues.some(v=>v.code==='comparison-unbound'));});
  check('反例：标签碰撞被检出',()=>{const model=structuredClone(R.build(samples.smallStack).geometry),labels=model.labels.filter(v=>v.role==='value');labels[0].box={...labels[1].box};assert.ok(R.auditLayout(model).issues.some(v=>v.code==='label-collision'));});
  check('反例：引线归属错位被检出',()=>{const model=structuredClone(R.build(samples.smallStack).geometry);model.routes.find(v=>v.role==='leader').points[0].x+=4;assert.ok(R.auditLayout(model).issues.some(v=>v.code==='leader-unbound'));});
  check('反例：层箭头方向与原值相反须失败',()=>{const model=structuredClone(R.build(samples.smallStack).geometry),r=model.routes.find(v=>v.space==='layer-value');r.arrowAt.x=r.arrowFrom.x+10;assert.ok(R.auditLayout(model).issues.some(v=>v.code==='layer-arrow-direction'));});
  check('层值增加及不变仍按共同零起点',()=>{for(const value of [.8,.5]){const spec=structuredClone(samples.smallStack);spec.items[1].segments[2].value=value;const r=R.build(spec).geometry.routes.find(v=>v.space==='layer-value');assert.equal(Math.sign(r.arrowAt.x-r.arrowFrom.x),Math.sign(value-.5));}});
  const result={ok:true,checks,samples:Object.keys(samples),measurement:'fontkit-tnum',scope:'静态 SVG 生成计算与布局；浏览器实际字体/几何及最终 PDF 另验'};console.log(JSON.stringify(result,null,2));return result;
}
module.exports={samples,run};if(require.main===module)run();
